version: '3'

env:
  BIN_DIR: bin
  APP_NAME: api
  COVERAGE_REPORTS_DIR: reports
  MIGRATIONS_DIR: migrations
tasks:

  install-go:
    desc: Download Go, install it, and add it to the PATH. Requires sudo.
    cmds:
      - wget "https://go.dev/dl/go$GO_VERSION.linux-amd64.tar.gz"
      - sudo rm -rf $GO_INSTALL_DIR/go
      - sudo tar -C $GO_INSTALL_DIR -xzf go$GO_VERSION.linux-amd64.tar.gz
      - echo 'export PATH=$PATH:/usr/local/go/bin' >> $HOME/.bashrc
      - echo 'export GOPATH=$HOME/go' >> $HOME/.bashrc
      - echo 'export PATH=$PATH:$GOPATH/bin' >> $HOME/.bashrc
      - echo 'export GO111MODULE=on' >> $HOME/.bashrc
      - rm go$GO_VERSION.linux-amd64.tar.gz
      - go version
    env:
      GO_VERSION: 1.21.1
      GO_INSTALL_DIR: /usr/local
  install-gotestdox:
    desc: Install gotestdox
    cmds:
      - go install github.com/bitfield/gotestdox/cmd/gotestdox@latest
  install-golangci-lint:
    desc: Install golangci-lint
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.54.2
  lint:
    desc: Static code analysis
    deps: [install-golangci-lint]
    cmds:
      - golangci-lint run -v
  test:
    desc: Run all tests with coverage
    cmds:
      - mkdir -p $COVERAGE_REPORTS_DIR
      - go test ./... -coverprofile=$COVERAGE_REPORTS_DIR/coverage.out

  gotestdox:
    desc: Formats Go test results as readable documentation
    deps: [install-gotestdox]
    cmds:
      - gotestdox ./...
  # coverage-check:
  #   desc: Check that coverage is above a threshold
  #   deps: [test]
  #   cmds:
  #     - go tool cover -func=$COVERAGE_REPORTS_DIR/coverage.out | grep total | awk '{print $3}' | awk -F. '{print $1}' | xargs -I{} test {} -ge $COVERAGE_THRESHOLD || (echo "Coverage is below threshold of $COVERAGE_THRESHOLD" && exit 1)
  #   env:
  #     COVERAGE_THRESHOLD: 50
  generate-coverage-report:
    desc: Generate a coverage report in HTML
    deps: [test]
    cmds:
      - go tool cover -html=$COVERAGE_REPORTS_DIR/coverage.out -o $COVERAGE_REPORTS_DIR/coverage.html
  check-format:
    desc: Check code formatting
    cmds:
      - go fmt ./...
  build:
    desc: Build the application
    cmds:
      - mkdir -p $BIN_DIR
      - go build -o $BIN_DIR/$APP_NAME ./cmd/api
  run:
    desc: Run the application
    deps: [build]
    cmds:
      - $BIN_DIR/$APP_NAME
  clean:
    desc: Remove all generated files
    cmds:
      - rm -rf $BIN_DIR
      - rm -rf $COVERAGE_REPORTS_DIR  

  help:
    desc: show config flags
    cmds:
      - $BIN_DIR/$APP_NAME -help
    deps: [build]
  migrate-new: 
    desc: task migrate -- [migration_pair_name]
    cmds:
      - migrate create -seq -ext=.sql -dir=$MIGRATIONS_DIR {{.CLI_ARGS}}
  migrate-up:
    desc: execute migrations
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=$GREENLIGHT_DB_DSN up
  migrate-down:
    desc: down all migrations
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=$GREENLIGHT_DB_DSN down
  migrate-goto:
    desc: migrate to a specific version
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=$GREENLIGHT_DB_DSN  goto {{.CLI_ARGS}}
  migrate-force:
    desc: used for fixing errors in SQL migrations
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=$GREENLIGHT_DB_DSN force {{.CLI_ARGS}}  
      
  migrate-version:
    desc: show current version
    cmds:
      - migrate -path=$MIGRATIONS_DIR -database=$GREENLIGHT_DB_DSN version
